#!/usr/bin/env bash

# colors!

RED="\033[0;31m" #red
GREEN="\033[0;32m" #green
YELLOW="\033[0;33m" #yellow
BLUE="\033[0;34m" #blue
CYAN="\033[0;36m" #cyan
PURPLE="\033[0;35m" #purple

# text craziness
BLINK="\033[05m" #blink
RED_BLINK="\033[0;31;5m" #red blink

# text format reset
COLOR_RESET="\033[0m"


base_port=$1
remote_base_port=$2
my_hostname=$3

listen_port=`expr $base_port + 1`

nch_dir=/tmp/nch

mkdir -p $nch_dir
publishing_to_ports_file=$nch_dir/${base_port}_publish_to.txt
echo -n "" > $publishing_to_ports_file

listening_on_ports_file=$nch_dir/${base_port}_subscribe_to.txt
echo -n "" > $listening_on_ports_file


listen_file=$nch_dir/hns.txt


function listen {
  echo "||| Listening for publish requests on $base_port..."
  nc -kdl $base_port | while IFS= read -r latest; do
    if [ "$latest" != "" ]; then
      hostname=`echo $latest | awk -F',' '{print $1}'`
      port=`echo $latest | awk -F',' '{print $2}'`
      echo "||| Got a publish to request from $hostname $port"

      publish_to_client $hostname $port

      subscribe_to_client $hostname
    fi
  done
  echo "done listening ..."
}

function listen_to_hostname_on_port {
  local hostname=$1
  local use_port=$2
  nc -kdl $use_port | while IFS= read -r message ; do
    echo -e "$YELLOW$hostname$COLOR_RESET @ `date +%H:%M:%S`"
    echo "    ${message}"
  done
  echo "stopped listening to $hostname on $use_port ..."
}

function subscribe_to_client {
  local hostname=$1
  local subscrption=`grep "$hostname," $listening_on_ports_file`
  if [[ -z "${subscrption}" ]]; then
    listen_port=`expr $listen_port + 1`
    local use_port=$listen_port
    echo ${hostname},$use_port >> $listening_on_ports_file
    echo "||| Subscribing to $hostname on $use_port..."
    listen_to_hostname_on_port $hostname $use_port &
    echo "||| Opened listener on $use_port for messages from $hostname..."
    echo "||| Requesting subscription from $hostname on $remote_base_port back to me at $my_hostname,$use_port"
    echo $my_hostname,$use_port | nc $hostname $remote_base_port &
  fi
}

function send_msg {
  hostname=$1
  port=$2
  shift
  shift
  echo ${@} | nc $hostname $port
}


# a publish_to is a hostname and port we remember and send all messages to in
# the future
function publish_to_client {
  hostname=$1
  port=$2
  echo "$hostname,$port" >> $publishing_to_ports_file
  echo "||| Will publish to $hostname at $port"
}

listen &

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

while IFS= read -r line; do
  if [[ $line =~ ^\+\+.*$ ]]; then
    hostname=`echo $line | cut -c 3-`
    subscribe_to_client $hostname
  else
    while read client; do
      hostname=`echo $client | awk -F',' '{print $1}'`
      port=`echo $client | awk -F',' '{print $2}'`
      if [[ -z "$hostname" &&  -z "$port" ]]; then
        echo "skipping empty parse"
      else
        send_msg $hostname $port $line
      fi
    done <$publishing_to_ports_file
  fi
done

